project:
  type: website
  output-dir: docs

website:
  title: "Fake News Detection"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: data.qmd
        text: Dataset
      - href: preprocess.qmd
        text: Data Preprocessing
      - href: vectorization.qmd
        text: Vectorization
      - href: model.qmd
        text: Model 
  page-footer: 
    left: "© 2025 Gireeshee Pendela"